---
ID: "db3ae0d8-c7c2-40d2-89ff-ceef528ff00d"
Parent: "66ee80c4-9b58-40f0-b2e2-6b163d33a19a"
Template: "66ee80c4-9b58-40f0-b2e2-6b163d33a19a"
Path: /sitecore/templates/Project/hztl/Headless Tenant/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240312T184430Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8a821ae4-be1f-42dd-a5ed-49ca62219ce4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240312T184430Z
